//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public int VendingMachineId { get; set; }
        public int DrinkId { get; set; }
        public int AfterUpdate { get; set; }
        public int Profit { get; set; }
    
        public virtual Drinks Drinks { get; set; }
    }
}
